/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.daycare.gui;

import edu.neu.csye6200.daycare.DayCare;
import edu.neu.csye6200.daycare.immunization.Immunization;
import edu.neu.csye6200.daycare.student.Student;
import edu.neu.csye6200.daycare.student.StudentGroup;
import static edu.neu.csye6200.daycare.student.StudentGroup.GROUP_A;
import static edu.neu.csye6200.daycare.student.StudentGroup.GROUP_B;
import static edu.neu.csye6200.daycare.student.StudentGroup.GROUP_C;
import static edu.neu.csye6200.daycare.student.StudentGroup.GROUP_D;
import static edu.neu.csye6200.daycare.student.StudentGroup.GROUP_E;
import static edu.neu.csye6200.daycare.student.StudentGroup.GROUP_F;
import java.awt.Dialog.ModalityType;
import java.awt.FlowLayout;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author anjali
 */
public class AddStudentUI extends javax.swing.JFrame {
    
    
    /**
     * Creates new form UserInterface
     */
    Immunization imz;
    Student obj;
    
    public AddStudentUI() {
        initComponents();
        imz = new Immunization();
        obj = new Student();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("StudentID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("AddStudent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("Registration Date");

        jLabel5.setText("Parent's Name");

        jLabel6.setText("Address");

        jLabel7.setText("Phone no.");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel11.setText("Sex");

        jLabel12.setText("Assign student to");

        jLabel13.setText("TeacherID");

        jLabel14.setText("ClassID");

        jLabel15.setText("Student Information");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add Vaccine Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //called when Add student button is pressed
        DayCare dc = DayCare.getInstance();
        
        String SId = jTextField1.getText();
        int s_id = Integer.parseInt(SId);
        obj.setStudentID(s_id);
        
        String name = jTextField2.getText();
        obj.setName(name);
        
        String sAge = jTextField5.getText();
        int age = Integer.parseInt(sAge);
        obj.setAge(age);
       
        obj.setGroupID(age);
        
        String sex = jTextField10.getText();
        obj.setSex(sex);
        
        String parentName = jTextField6.getText();
        obj.setParentsName(parentName);
        
        String address = jTextField7.getText();
        obj.setAddress(address);
        
        String phNo = jTextField8.getText();
        obj.setPhoneNumber(phNo);
        
        String date = jTextField9.getText();
        try {
            Date regDate = new SimpleDateFormat("dd/MM/yyyy").parse(date);
            obj.setRegistrationDate(regDate);
        } catch (ParseException ex) {
            System.out.println("Exception while entering date");
        }
               
        String tId = jTextField11.getText();
        int t_id = Integer.parseInt(tId);
        obj.setTeacherID(t_id);
        
        String classID = jTextField12.getText();
        obj.setClassID(classID);
        
        dc.addStudent(obj);
        
        imz.setStudentID(obj.getStudentID());
        
       
//       System.out.println("I should be called after DONE");
//       if(i1.polioCB.isSelected()){
//           System.out.println("Polio Vaccine was given");
//             //Write "Given" to imz.csv
//            imz.setPolioStatus(true);
//             
//            String polioDate = i1.datePolio.getText();
//             //get date from text field, convert string to date
//             try {
//            Date polio_date = new SimpleDateFormat("dd/MM/yyyy").parse(date);
//            imz.setPolioDate(polio_date);
//            System.out.println("Date set successfully");
//            
//            } catch (ParseException ex) {
//            System.out.println("Exception while entering Vaccine date");
//            }
//             
//            imz.setMaxPolioDoses();
//            
//            String polioDosesDone = i1.polioDose.getText();
//            int polioPastDoses = Integer.parseInt(polioDosesDone);
//            imz.setPolioDosesDone(polioPastDoses);
//            
//            int remPolDoses = imz.getMaxPolioDoses()-polioPastDoses;
//            imz.setRemainingPolioDoses(remPolDoses);
//        }   
//        else {
//             System.out.println("Polio Vaccine was not given");
//             //Write "Not Given" to imz.csv
//             imz.setPolioStatus(false);
//       }
       
       
       /*if(jCheckBox1.isSelected()){
             System.out.println("Polio Vaccine was given");
             //Write "Given" to imz.csv
             imz.setPolioStatus(true);
             
             String polioDate = jTextField3.getText();
             //get date from text field, convert string to date
             try {
            Date polio_date = new SimpleDateFormat("dd/MM/yyyy").parse(date);
            imz.setPolioDate(polio_date);
            System.out.println("Date set successfully");
            
            } catch (ParseException ex) {
            System.out.println("Exception while entering Vaccine date");
            }
             
            imz.setMaxPolioDoses();
            
            String polioDosesDone = jTextField13.getText();
            int polioPastDoses = Integer.parseInt(polioDosesDone);
            imz.setPolioDosesDone(polioPastDoses);
            
            int remPolDoses = imz.getMaxPolioDoses()-polioPastDoses;
            imz.setRemainingPolioDoses(remPolDoses);
        }   
        else {
             System.out.println("Polio Vaccine was not given");
             //Write "Not Given" to imz.csv
             imz.setPolioStatus(false);
        }
       
         if(jCheckBox2.isSelected()){
             System.out.println("TB Vaccine was given");
             //Write "Given" to imz.csv
         }else{
             System.out.println("TB Vaccine was not given");
             //Write "Not Given" to imz.csv
         }
       */
         
         dc.addImmzDetails(imz);
         
        JOptionPane.showMessageDialog(null, "Student Added", "InfoBox: " + "Success", JOptionPane.INFORMATION_MESSAGE); 
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Clear button
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private StudentGroup getGrpIdFromAge(int age){
        
        if(age>=6 && age<=12)
                return GROUP_A;
            else if(age>=13 && age<=24)
                return GROUP_B;
            else if(age>=25 && age<=35)
                return GROUP_C;
            else if(age>=36 && age<=47)
                return GROUP_D;
            else if(age>=48 && age<=59)
                return GROUP_E;
            else return GROUP_F;
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //This will be called when add vaccine is pressed
        String sAge = jTextField5.getText();
        int age = Integer.parseInt(sAge);
        if(age<=24){
            System.out.println("Open a dialog box");
            AddStudentUI frame = new AddStudentUI();
            JDialog dA = new JDialog(new AddStudentUI(), true);
            //JDialog DialogBox_A = new JDialog();
            
            //adding interface for polio
            JCheckBox polioCB = new JCheckBox("Polio"); 
            JTextField polioDose = new JTextField(10);
            JTextField polioDate = new JTextField(10);
            //add labels
            
            //add to dialog box
            dA.add(polioCB);
            dA.add(polioDose);
            dA.add(polioDate);
            
            //add interface for other vaccines
            //add to dialog box
            
            JButton submitButton = new JButton ("Submit");

            submitButton.addActionListener (new ActionListener()  {  
                public void actionPerformed( ActionEvent e )  {
                    
                     
                      String sAge = jTextField5.getText();
                      int age = Integer.parseInt(sAge); 
                     StudentGroup id = getGrpIdFromAge(age);
                     //imz.setGroupID(obj.getGroupID());
                     imz.setGroupID(id);
                     
                    System.out.println(polioDate.getText());
                    try {
                        Date polio_date = new SimpleDateFormat("dd/MM/yyyy").parse(polioDate.getText());
                        //convert to date from String for other vaccines
                        
                        imz.setPolioDate(polio_date); 
                        //set other dates imz object
                    } catch (Exception ex) {
                        System.out.println("Exception while parsing date " + ex);
                    }
                    if(polioCB.isSelected()){
                        imz.setPolioStatus(true);
                        imz.setPolioDosesDone(Integer.parseInt(polioDose.getText()));
                    }
                    //write a if loop for all vaccines
                    
                    imz.setMaxPolioDoses();
                    int remPolDoses = imz.getMaxPolioDoses()-imz.getPolioDosesDone();
                    imz.setRemainingPolioDoses(remPolDoses);
                    //set Max & rem doses for other vaccines
                    
                    //close dialog box
                }  
            }); 
            
            dA.add(submitButton);
            dA.setLayout( new FlowLayout() );     
            dA.setSize(500,500);    
            dA.setVisible(true);
   
        }
        if(age>24){
        //new AddImz_2().setVisible(true);
        }
        else if(sAge.isEmpty()){
            //JOptionPane.showMessageDialog(null, "Please enter age", "InfoBox: " + "Error", JOptionPane.INFORMATION_MESSAGE);      
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserInterface().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
